services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
        - path: ./backend/src
          target: /app/src
          action: sync
        - path: ./backend/build.gradle
          target: /app/build.gradle
          action: sync
        - path: ./backend/settings.gradle
          target: /app/settings.gradle
          action: sync

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .next/
    depends_on:
      - backend
